# -----------------------------------------------------------------------------
# openapi/paths/businesses/addresses/addresses-by-id.openapi.yaml
# -----------------------------------------------------------------------------

# GET /businesses/{businessId}/addresses/{addressId}
get:
  tags:
    - Business Addresses
  summary:      Retrieve a Business address 
  description:  Retrieve a Business address
  parameters:
    - $ref:     '../../../components/parameters/businessId.param.yaml'
    - $ref:     '../../../components/parameters/addressId.param.yaml'
    - $ref:     '../../../components/headers/xRequestId.param.yaml'
  responses:
    '200':
      description:  'OK'
      content:
        application/json:
          schema:
            properties:
              address:
                $ref: '../../../components/schemas/address/address.schema.yaml'

# PATCH /businesses/{businessId}/addresses/{addressId}
patch:
  tags:
    - Business Addresses
  summary:      Update a Business address 
  description:  Update a Business address
  parameters:
    - $ref:     '../../../components/parameters/businessId.param.yaml'
    - $ref:     '../../../components/parameters/addressId.param.yaml'
    - $ref:     '../../../components/headers/xRequestId.param.yaml'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../components/schemas/address/new-address.schema.yaml'
  responses:
    '201':
      description:  'OK'
      content:
        application/json:
          schema:
            properties:
              address:
                $ref: '../../../components/schemas/address/address.schema.yaml'