# -----------------------------------------------------------------------------
# openapi/openapi.yaml
# -----------------------------------------------------------------------------
openapi: 3.0.2
info:
  version:        1.0.0
  title:          Example.com
  termsOfService: 'https://example.com/terms/'
  contact:
    email:  contact@example.com
    url:    'http://example.com/contact'
  license:
    name:   Apache 2.0
    url:    'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url:    'https://redocly.github.io/openapi-template/logo.png'
  description: >
    Protoype BaaS APIs for starting ConNext Bank APIs. The prototype contains
    the Consumer, Business, Accounts, Transactions, and Card APIs.
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
tags:
  - name:         Consumer
    description:  Consumer resource APIs
  - name:         Business
    description:  Business resource APIs
  - name:         Account
    description:  Bank Account resource APIs
  - name:         Transaction
    description:  Transactions for a bank account APIs
paths:
  /consumers:
    $ref: './paths/consumers/consumers.openapi.yaml'
  /consumers/{consumerId}:
    $ref: './paths/consumers/consumers@{consumerId}.openapi.yaml'
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
