# -----------------------------------------------------------------------------
# openapi/components/schemas/consumers/contacts/contacts.openapi.yaml
# -----------------------------------------------------------------------------

# GET /consumers/{consumerId}/contacts
get:
  tags:
    - Consumer Contacts
  summary:      Retrieve all of a Consumer's contact details
  description:  Retrieve all of a Consumer's contact details
  parameters:
    - $ref: '../../../components/parameters/consumerId.param.yaml'
    - $ref: '../../../components/headers/xRequestId.param.yaml'
  responses:
    '200':
      description:  'OK'
      content:
        application/json:
          schema:
            $ref: '../../../components/schemas/contact/contact-list.schema.yaml'

# POST /consumers/{consumerId}/contacts
post:
  tags:
    - Consumer Contacts
  summary:      Add contact details for a Consumer
  description:  Add new email or phone number for a Consumer
  parameters:
    - $ref: '../../../components/parameters/consumerId.param.yaml'
    - $ref: '../../../components/headers/xRequestId.param.yaml'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../components/schemas/contact/new-contact.schema.yaml'
  responses:
    '201':
      description:  'OK'
      content:
        application/json:
          schema:
            properties:
              contact:
                $ref: '../../../components/schemas/contact/contact.schema.yaml'