# ---------------------------------------------------------------------------------------
# openapi/components/schemas/consumers@{consumerId}-addresses@{addressId}.openapi.yaml
# ---------------------------------------------------------------------------------------

# GET /consumers/{consumerId}/addresses/{addressId}
get:
  tags:
    - Consumer Address
  summary:      Retrieve a Consumer address 
  description:  Retrieve a Consumer address
  parameters:
    - $ref: '../../../components/parameters/consumerId.param.yaml'
    - $ref: '../../../components/parameters/addressId.param.yaml'
    - $ref: '../../../components/headers/xRequestId.param.yaml'
  responses:
    '200':
      description:  'OK'
      content:
        application/json:
          schema:
            properties:
              address:
                $ref: '../../../components/schemas/address/address.schema.yaml'

# PATCH /consumers/{consumerId}/address/{addressId}
patch:
  tags:
    - Consumer Address
  summary:      Update a Consumer address 
  description:  Update a Consumer address
  parameters:
    - $ref: '../../../components/parameters/consumerId.param.yaml'
    - $ref: '../../../components/parameters/addressId.param.yaml'
    - $ref: '../../../components/headers/xRequestId.param.yaml'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../components/schemas/address/new-address.schema.yaml'
  responses:
    '201':
      description:  'OK'
      content:
        application/json:
          schema:
            properties:
              address:
                $ref: '../../../components/schemas/address/address.schema.yaml'